#!/bin/bash

echo "Baixando uri-auto."
wget -O $HOME/.tst/bin/uri-auto 
https://raw.githubusercontent.com/felipemarinho97/uri-auto/master/uri-auto
chmod +x $HOME/.tst/bin/uri-auto
echo "uri-auto instalado com sucesso.. digite "uri-auto --help" no seu terminal para uso do comando"
